### PR TITLE
Add support for mobile web

### PR DESCRIPTION
**Pull request by corcoran**
Implemented using the same detection method used in Android (<85% visible screen).

### CODE REVIEW

**Comment by MisterJimson** [comment]
Thanks for the PR!

Unfortunately I wasn't able to get this to work in my tests with the example app. Tested on iOS Safari and Android Chrome.

https://user-images.githubusercontent.com/7351329/152803843-ea6372fb-9d55-41bf-82ae-fc419e765262.MP4

https://user-images.githubusercontent.com/7351329/152803872-e8ad436e-8ce3-45e5-94d7-a190f86b13eb.mov

**Comment by MisterJimson** [comment]
AH nevermind! It was using the web package from pub.dev. Need to retest! My bad.

**Comment by corcoran** [comment]
Hm strange, I didn't have an issue running locally on Chrome. I used a dependency_override to force the example app to use the correct flutter_keyboard_visibility_web override however.
```
dependency_overrides:
  flutter_keyboard_visibility_web:
    git:
      url: 'https://github.com/corcoran/flutter_keyboard_visibility'
      path: 'flutter_keyboard_visibility_web'
```

https://user-images.githubusercontent.com/1402817/152857798-fac90ded-208e-451c-b470-54760fcae64f.mp4

**Comment by MisterJimson** [comment]
Due to the above concerns I am going to close this for now. I haven't been able to work around them in my testing.

**Pull request closed without merging**
