### PR TITLE
feat: upgraded gradle to 8.1.0 and kotlin to 1.8.22

### PR DESCRIPTION
**Pull request by larssn**
Upgrades gradle to 8.1.0 and kotlin 1.8.22. Also fixes a few gradle deprecation warnings, and an incorrect kotlin-stdlib-jdk version to Java 8.

### CODE REVIEW

**Comment by MisterJimson** [comment]
Last time I tried this it broke for everyone on Gradle 7, is that ok? What are other libs doing?

I guess we bump the major and flag in the release notes?

**Comment by larssn** [comment]
Up to you, but I'd personally bump the major if you've experienced problems with it in the past.

I checked a few other plugins - android_id and a few firebase plugins. They're running gradle 8, so I think it's fine. 🙂
It's the way of things, in any case, in order to be forward compatible.

**Comment by MisterJimson** [comment]
Hmm some of the official plugins still seem to be on 7

https://github.com/flutter/packages/blob/f8931024c4cb4ee0631527f11c2b6d4e2c1b65bc/packages/camera/camera_android/android/build.gradle#L12

**Comment by larssn** [comment]
I wouldn't be surprised by that. The Flutter Team aren't very good at keeping gradle files up to date.

Still, I'd bump the major version. No one can complain if a major bump has potentially breaking changes. That's the name of the game. 🙂

**Comment by larssn** [comment]
On review, I think you're right. We should hold back on gradle >8 until Flutter is ready for it.

**Pull request closed without merging**
