### PR TITLE
chore: update Gradle to 8.2 and AGP to 8.2.0

### PR DESCRIPTION
**Pull request by thearaks**
Please accept this pull request and release a new version of the library since it's blocking compilation with Flutter 3.16.
Thank you!

### CODE REVIEW

**Comment by MisterJimson** [comment]
Looking at this. In the mean time can you see if 6.0.0-beta solves your problem as well? Ideally the library works for Gradle 7 and 8.

**Comment by MisterJimson** [comment]
I've just tested 6.0.0-beta on a fresh counter app created with Flutter 3.16.4 so I'm hoping this isn't needed?

**Comment by thearaks** [comment]
Hi @MisterJimson,
Gradle 7 is probably enough for Flutter 3.16 but Gradle 8.0+ is needed with the latest versions of Android Studio and for every app that includes at least a plugin that's been migrated to Gradle 8.0+ and requires the new build scripts syntax/features.

I'd release a new version with Gradle 8.0+ since every app is being migrated to the newest Gradle versions and I think that Flutter soon will move to 8.0+ as "default" Gradle version.

At the moment I have to use my forked version since I cannot include this plugin in my app that's using Gradle 8.0+ (and I can't downgrade it since other plugins requires 8.0+).

**Comment by MisterJimson** [comment]
Hmm. I tested with Android Studio 2023.1.1 and it worked for me. I'll look into it deeper.

Just to be clear, did you test your app with 6.0.0-beta that was published yesterday?

**Comment by thearaks** [comment]
Hi @MisterJimson, sorry for this late update, I've been busy with some other work projects.
I've run a test build with version 6.0.0-beta in an app that's using Gradle 8.2 and the build completed successfully!

**Comment by MisterJimson** [comment]
Thank you! I'll close this PR for now and will likely reopen when Gradle 8 is mandatory or Gradle 7 is fully deprecated.

**Pull request closed without merging**
